version: '3'

services:
  db:
    image: postgres:16-alpine
    container_name: db
    restart: unless-stopped
    env_file: ./.env

    environment:
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: $PG_DATABASE

    ports:
      - $PG_PORT:$PG_PORT

  app:
    container_name: clark-mvp
    build: ./
    env_file:
      - path: ./.env
        required: false
      - path: ./.env.docker
        required: true
    environment:
      - PG_HOST=$PG_HOST_DOCKER

    ports:
      - 3000:3000

    volumes:
      - ./:/src/
      - nodemodules:/src/node_modules

    links:
      - db
    depends_on:
      - db

volumes:
  nodemodules: {}
